### ISSUE TITLE
Drop hls.js dependency

### ISSUE THREAD

**Issue by niklaskorz** [matvp91/indigo-player#10]
Shaka-player supports MPEG DASH _and_ HLS playback: https://github.com/google/shaka-player#hls-features

**Comment by matvp91** [comment]
I went with HLS.js because of my own experience with the package (which has been great). Shaka's implementation is a whole lot smaller thus this makes sense. As for now, I'd have to see how good Shaka is for HLS.

I'll leave this issue open in order for other people to give feedback.

**Comment by vikasbnsl** [comment]
I had to use video js as SHAKA does not support AES encription Also it has some more issues like
https://github.com/google/shaka-player/issues/1625

**Comment by vikasbnsl** [comment]
I had to use video js as SHAKA does not support AES encription Also it has some more issues like
https://github.com/google/shaka-player/issues/1625

**Comment by matvp91** [comment]
Let's stick with HLS.js. Media modules are chunked and not bundled with the main module, which means HLS.js doesn't even hit your browser if it's not needed.
