### ISSUE TITLE
KeyboardNavigationExtension - nagivate through the video with keyboard shortcuts.

### ISSUE THREAD

**Issue by matvp91** [matvp91/indigo-player#20]
This extension takes care of keyboard navigation.

- "m" - toggle mute
- "space" - toggle play pause
- "up arrow" - increase volume by 0.1
- "down arrow" - decrease volume by 0.1
- "left arrow" - go back 15 seconds in time (but do not go lower than 0)
- "right arrow" - go forwards 15 seconds in time (but do not go higher than the duration of the asset)
- "f" - toggle fullscreen

Also keeps track of whether the player is focused or not (if document.activeElement is part of the current player instance). This way we don't always hijack the keyboard navigation. The following options can be provided by the config (and can be handled by the extension loader):

"keyboardNavigation":
- true - keyboard navigation is always on
- false - keyboard navigation is not even loaded
- "focus" - only listen to the keystrokes when the player has the focus, this is the default behavior

**Comment by stoicbuddha** [comment]
Do you have any plans on moving this to the README?

**Comment by matvp91** [comment]
I've created an issue to keep track of adding them in the docs (instead of the README): https://github.com/matvp91/indigo-player/issues/34
