### ISSUE TITLE
Unable to go fullscreen on iOS

### ISSUE THREAD

**Issue by Janhouse** [matvp91/indigo-player#40]
I am unable to view full screen video on latest iOS. Clicking that tiny button (which is way too small for mobile) or double tapping the video doesn't do anything.

**Comment by matvp91** [comment]
What iOS version & which mobile browser do you use? There are iOS Safari versions where native fullscreen is not supported and a fallback is required, which is not implemented yet.

Could you provide me a screenshot of the buttons that you find too small?

**Comment by Janhouse** [comment]
iOS 12.3.1 and tried in latest stable Safari and Firefox, they both work the same way.

Here is the screenshot. All of the buttons are too small. 
![File](https://user-images.githubusercontent.com/1036439/59030071-95a36300-8868-11e9-9f0f-f280f5dc2fc5.jpg)

Tested with this HTML
```<!DOCTYPE html>
<html>
  <head><title>Stream</title></head>
  <body>
    <style>
	* {
		margin: 0;
		padding: 0;
	}
	body {background-color: black}
	.igui_timestat_duration {display:none!important}
	.igui_settings_select .igui_button_name-select-option:nth-child(2) {display:none!important}
	.igui_container_controls_seekbar {display:none}
    </style>
    <div id="playerContainer"></div>
    <script src="https://cdn.jsdelivr.net/npm/indigo-player@1/lib/indigo-player.js"></script>
    <script>

      var vtag = document.createElement("video"); var hlsSupported = !!vtag.canPlayType && !!vtag.canPlayType("application/x-mpegurl");

      var source='/uber-dash/raw.mpd';
      var format='dash';

      if(hlsSupported) {
        format='hls';
        source='/uber-hls/raw.m3u8';
      }

      const config = {
        autoplay: true,
        sources: [
          {
            type: format,
            src: source,
          }
        ],
      };

      const element = document.getElementById('playerContainer');
      const player = IndigoPlayer.init(element, config);
    </script>
  </body>
</html>```

**Comment by matvp91** [comment]
Regarding the small layout, it's because your page is rendered as a web page. Mobile pages are best served with the proper viewport sizing (see: https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag).

Adding `<meta name="viewport" content="width=device-width, initial-scale=1">` in your `head` tag should make the player properly scale on mobile.

As for not being able to fullscreen on iOS, I'll grab an iPhone and provide a fix or fallback soonish.

**Comment by Janhouse** [comment]
@matvp91, thank you! 😃

**Comment by nums** [comment]
Hello,

I have made support for webkitEnterFullscreen here : https://github.com/matvp91/indigo-player/pull/46/commits/8267a5bef8044bb413ca02149a768ee82d2bb8ce
