### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by L3rchal** [matvp91/indigo-player#9]
Will be safari support added in near future?

**Comment by matvp91** [comment]
Can you provide more information? Which streaming format, DRM, ads and which Safari version?

**Comment by SchjarvenUtviklere** [comment]
Safari works. 
They use HLS, and Mp4. 

but to get Autoplay on iPhone then it requires that you to add the **playsinline** parameter to your video tag.

<video id="contentElement" playsinline muted>

https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/

**Comment by matvp91** [comment]
The player module adds the playsinline attribute by default, see https://github.com/matvp91/indigo-player/blob/master/src/player/HTML5Player/HTML5Player.ts for reference.

As for autoplay restrictions: if autoplay is enabled in the config, the player will attempt to autoplay and if it fails, it will be handled gracefully (& show a play button instead).

**Comment by ppkh** [comment]
> The player module adds the playsinline attribute by default, see https://github.com/matvp91/indigo-player/blob/master/src/player/HTML5Player/HTML5Player.ts for reference.
> 
> As for autoplay restrictions: if autoplay is enabled in the config, the player will attempt to autoplay and if it fails, it will be handled gracefully (& show a play button instead).

I know this issue is closed, but is this behaviour still the same?

I am expecting with `autoPlay: false` to get a play button displayed, but after firing `.init()`, it autoplays.
